<pre class='metadata'>
Title: Scroll Snap for Single-Axis Scroll Containers
Shortname: single-axis-scroll-snap
Level: None
Status: w3c/UD
Repository: explainers-by-googlers/single-axis-scroll-snap
URL: https://explainers-by-googlers.github.io/single-axis-scroll-snap
Editor: David Liu, Google https://google.com, lcdavid@google.com
Abstract: Extensions to CSS Scroll Snap to support per-axis snap area propagation across single-axis scroll containers.
Markup Shorthands: markdown yes, css no
Complain About: accidental-2119 yes, missing-example-ids yes
Assume Explicit For: yes
Die On: warning
WPT Path Prefix: TODO-API-LABEL
WPT Display: closed
Include MDN Panels: if possible
Include Can I Use Panels: yes
</pre>

Introduction {#intro}
=====================

For now, see the <a href=[REPOSITORYURL]>explainer</a>.

See [https://garykac.github.io/procspec/](https://garykac.github.io/procspec/),
[https://dlaliberte.github.io/bikeshed-intro/index.html](https://dlaliberte.github.io/bikeshed-intro/index.html),
and [https://speced.github.io/bikeshed/](https://speced.github.io/bikeshed/) to get started on your
specification.
